### ISSUE TITLE
High CPU utilization - 80%+ 

### ISSUE THREAD

**Issue by dandv** [bigspaceship/shine.js#12]
If I mouse around at normal speed [in the demo](http://bigspaceship.github.io/shine.js/), CPU utilization jumps to 80% - 90%. I'm using Chrome 43.0.2357.124 m on Windows 7 on a Dell E7450 Core i5 with some an integrated GPU (which is perfectly capable of handling [this demo](https://zolmeister.com/2013/08/tanzania-africa-in-175-million-particles.html) at <40% CPU).

**Comment by benjaminbojko** [comment]
Shine uses CSS drop shadows, whereas the demo you referenced uses WebGL particles. Drop shadows are rendered entirely by the browser and there's not much more to be done to optimize them. Shine creates multiple drop shadows and merely changes their offset. Most browsers render drop shadows on the CPU, but if you're using Chrome (or better yet, Chrome Canary), you can force it to rasterize everything on the GPU. Copy/paste the following URL **[chrome://flags/#enable-gpu-rasterization](chrome://flags/#enable-gpu-rasterization)** and set the value for the _Enable GPU Rasterization_ drop down to _Force-enabled for all layers_.

What this will do is offload the rendering to the GPU and thus free CPU resources. On my Mac Pro, that reduces the CPU load from 85% to 15%. As you can see, there won't be much to optimize on the JS side since the majority of computation is browser internal rendering.
